;==============================================
;===== ConstDefine.INC
;==============================================
   UART_PORT        EQU   PT1
    UART_RXD_PIN    EQU   0
    UART_TXD_PIN    EQU   1
    
   WIFI_PWR_PORT    EQU   PT1
    WIFI_PWR_PIN    EQU   2

  IIC_SCL_PTEN    EQU   PT1EN
  IIC_SCL_PTPU    EQU   PT1PU
  IIC_SCL_PORT    EQU   PT1
   B_IIC_PIN_SCL  EQU   3

  IIC_SDA_PTEN    EQU   PT4EN
  IIC_SDA_PTPU    EQU   PT4PU
  IIC_SDA_PORT    EQU   PT4
   B_IIC_PIN_SDA  EQU   2

;  IIC_RDY_PTEN    EQU   PT1EN
;  IIC_RDY_PTPU    EQU   PT1PU
;  IIC_RDY_PORT    EQU   PT1
;   B_IIC_PIN_RDY  EQU   3



    
    