;==============================================================
;======= ISR_LED.ASM
;==============================================================
INTERRUPT_LED_ENTRY:
        INCF	R_LED_COUNT,F
		MOVLW	7
		SUBWF	R_LED_COUNT,W
		BTFSC	STATUS,C
		CLRF	R_LED_COUNT

		MOVLW	FFH              ; CLOSE ALL DISP
		MOVWF	PT2
		MOVWF	PT2CON
		MOVWF	LEDZCON
		MOVWF	R_LED_LIGHT
		
		CLRF	R_LED_DUTY
		
		MOVFW	R_LED_COUNT
		ADDPCW	
		GOTO	INTERRUPT_LED_P20
		GOTO	INTERRUPT_LED_P21
;		GOTO	INTERRUPT_LED_P22
		GOTO	INTERRUPT_LED_P23
		GOTO	INTERRUPT_LED_P24
		GOTO	INTERRUPT_LED_P25
		GOTO	INTERRUPT_LED_P26
		GOTO	INTERRUPT_LED_P27

INTERRUPT_LED_P20:		
    ; PT2.0
	    BTFSC   LED1,0         ; PT21
	    INCF	R_LED_DUTY,F 
	    BTFSC   LED1,6         ; PT23
	    INCF	R_LED_DUTY,F
	    BTFSC   LED2,2         ; PT24
	    INCF	R_LED_DUTY,F
	    BTFSC   LED4,6         ; PT25
	    INCF	R_LED_DUTY,F
	    BTFSC   LED2,3         ; PT26
	    INCF	R_LED_DUTY,F
	    BTFSC   LED7,0         ; PT27
	    INCF	R_LED_DUTY,F

	    BTFSC   LED1,0         ; PT21
	    BCF     R_LED_LIGHT,1
	    BTFSC   LED1,6         ; PT23
	    BCF     R_LED_LIGHT,3
	    BTFSC   LED2,2         ; PT24
	    BCF     R_LED_LIGHT,4
	    BTFSC   LED4,6         ; PT25
	    BCF     R_LED_LIGHT,5
	    BTFSC   LED2,3         ; PT26
	    BCF     R_LED_LIGHT,6
	    BTFSC   LED7,0         ; PT27
	    BCF     R_LED_LIGHT,7

		MOVLW 	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END

        BCF     R_LED_LIGHT,0
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON        ; 
		MOVWF	LEDTEST2      ; IO - HZ
		
		MOVLW	11111010B
		MOVWF	PT2
		
		GOTO	INTERRUPT_LED_END
		
INTERRUPT_LED_P21:		
    ; PT2.1
	    BTFSC	LED2,0      ; PT20
	    INCF	R_LED_DUTY,F
	    BTFSC	LED1,1      ; PT23
	    INCF	R_LED_DUTY,F
	    BTFSC	LED3,7      ; PT24
	    INCF	R_LED_DUTY,F
	    BTFSC	LED3,1      ; PT25
	    INCF	R_LED_DUTY,F
	    BTFSC	LED7,7      ; PT26
	    INCF	R_LED_DUTY,F
	    BTFSC	LED7,1      ; PT27
	    INCF	R_LED_DUTY,F

	    BTFSC	LED2,0      ; PT20
	    BCF		R_LED_LIGHT,0
	    BTFSC	LED1,1      ; PT23
	    BCF		R_LED_LIGHT,3
	    BTFSC	LED3,7      ; PT24
	    BCF		R_LED_LIGHT,4
	    BTFSC	LED3,1      ; PT25
	    BCF		R_LED_LIGHT,5
	    BTFSC	LED7,7      ; PT26
	    BCF		R_LED_LIGHT,6
	    BTFSC	LED7,1      ; PT27
	    BCF		R_LED_LIGHT,7

		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,1
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2      ; IO - HZ
				
		MOVLW	11111001B
		MOVWF	PT2
		
		GOTO	INTERRUPT_LED_END

INTERRUPT_LED_P23:		
		;PT2.3
		BTFSC	LED2,6        ; PT20
		INCF	R_LED_DUTY,F
		BTFSC	LED1,5        ; PT21
		INCF	R_LED_DUTY,F
		BTFSC	LED5,4        ; PT24
		INCF	R_LED_DUTY,F
		BTFSC	LED5,3        ; PT25
		INCF	R_LED_DUTY,F
		BTFSC	LED1,2        ; PT26
		INCF	R_LED_DUTY,F		
		BTFSC	LED7,3        ; PT27
		INCF	R_LED_DUTY,F

		BTFSC	LED2,6        ; PT20
		BCF		R_LED_LIGHT,0
		BTFSC	LED1,5        ; PT21
		BCF		R_LED_LIGHT,1
		BTFSC	LED5,4        ; PT24
		BCF		R_LED_LIGHT,4
		BTFSC	LED5,3        ; PT25
		BCF		R_LED_LIGHT,5
		BTFSC	LED1,2        ; PT26
		BCF		R_LED_LIGHT,6
        BTFSC	LED7,3        ; PT27
        BCF		R_LED_LIGHT,7
		
		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,3
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2      ; IO - HZ		
		
		MOVLW	11110011B
		MOVWF	PT2
		
		GOTO	INTERRUPT_LED_END

INTERRUPT_LED_P24:		
		;PT2.4
		BTFSC	LED2,4        ; PT20
		INCF	R_LED_DUTY,F
		BTFSC	LED5,6        ; PT21
		INCF	R_LED_DUTY,F
		BTFSC	LED5,2        ; PT23
		INCF	R_LED_DUTY,F
		BTFSC	LED4,4        ; PT25
		INCF	R_LED_DUTY,F
		BTFSC	LED4,3        ; PT26
		INCF	R_LED_DUTY,F
		BTFSC	LED7,4        ; PT27
		INCF	R_LED_DUTY,F

		BTFSC	LED2,4        ; PT20
		BCF		R_LED_LIGHT,0
		BTFSC	LED5,6        ; PT21
		BCF		R_LED_LIGHT,1
		BTFSC	LED5,2        ; PT23
		BCF		R_LED_LIGHT,3
		BTFSC	LED4,4        ; PT25
		BCF		R_LED_LIGHT,5
		BTFSC	LED4,3        ; PT26
		BCF		R_LED_LIGHT,6
		BTFSC	LED7,4        ; PT27
		BCF		R_LED_LIGHT,7
		
		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,4
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2      ; IO - HZ		
		
		MOVLW	11101011B
		MOVWF	PT2
		
		GOTO	INTERRUPT_LED_END

INTERRUPT_LED_P25:				
		;PT2.5
		BTFSC	LED3,6        ; PT20
		INCF	R_LED_DUTY,F
		BTFSC	LED3,5        ; PT21
		INCF	R_LED_DUTY,F
		BTFSC	LED1,7        ; PT23
		INCF	R_LED_DUTY,F
		BTFSC	LED4,2        ; PT24
		INCF	R_LED_DUTY,F
		BTFSC	LED3,4        ; PT26
		INCF	R_LED_DUTY,F
		BTFSC	LED7,5        ; PT27
		INCF	R_LED_DUTY,F
		
		BTFSC	LED3,6        ; PT20
		BCF		R_LED_LIGHT,0
		BTFSC	LED3,5        ; PT21
		BCF		R_LED_LIGHT,1
		BTFSC	LED1,7        ; PT23
		BCF		R_LED_LIGHT,3
		BTFSC	LED4,2        ; PT24
		BCF		R_LED_LIGHT,4
		BTFSC	LED3,4        ; PT26
		BCF		R_LED_LIGHT,6
		BTFSC	LED7,5        ; PT27
		BCF		R_LED_LIGHT,7
		
		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,5
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2      ; IO - HZ			
		
		MOVLW	11011011B
		MOVWF	PT2
		
		GOTO	INTERRUPT_LED_END

INTERRUPT_LED_P26:		
		;PT2.6
		BTFSC	LED1,3        ; PT20
		INCF	R_LED_DUTY,F
		BTFSC	LED6,7        ; PT21
		INCF	R_LED_DUTY,F
		BTFSC	LED1,4        ; PT23
		INCF	R_LED_DUTY,F
		BTFSC	LED3,3        ; PT24
		INCF	R_LED_DUTY,F
		BTFSC	LED3,2        ; PT25
		INCF	R_LED_DUTY,F		
		BTFSC	LED7,6        ; PT27
		INCF	R_LED_DUTY,F
		
		BTFSC	LED1,3        ; PT20
		BCF		R_LED_LIGHT,0
		BTFSC	LED6,7        ; PT21
		BCF		R_LED_LIGHT,1
		BTFSC	LED1,4        ; PT23
		BCF		R_LED_LIGHT,3
		BTFSC	LED3,3        ; PT24
		BCF		R_LED_LIGHT,4
		BTFSC	LED3,2        ; PT25
		BCF		R_LED_LIGHT,5
		BTFSC	LED7,6        ; PT27
		BCF		R_LED_LIGHT,7
		
		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,6		
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2      ; IO - HZ		

		MOVLW	10111011B
		MOVWF	PT2
		GOTO	INTERRUPT_LED_END

INTERRUPT_LED_P27:		
		;PT2.7
		BTFSC	LED6,0        ; PT20
		INCF	R_LED_DUTY,F
		BTFSC	LED6,1        ; PT21
		INCF	R_LED_DUTY,F
		BTFSC	LED6,3        ; PT23
		INCF	R_LED_DUTY,F
		BTFSC	LED6,4        ; PT24
		INCF	R_LED_DUTY,F
		BTFSC	LED6,5        ; PT25
		INCF	R_LED_DUTY,F		
		BTFSC	LED6,6        ; PT26
		INCF	R_LED_DUTY,F
		
		BTFSC	LED6,0        ; PT20
		BCF		R_LED_LIGHT,0
		BTFSC	LED6,1        ; PT21
		BCF		R_LED_LIGHT,1
		BTFSC	LED6,3        ; PT23
		BCF		R_LED_LIGHT,3
		BTFSC	LED6,4        ; PT24
		BCF		R_LED_LIGHT,4
		BTFSC	LED6,5        ; PT25
		BCF		R_LED_LIGHT,5
		BTFSC	LED6,6        ; PT26
		BCF		R_LED_LIGHT,6
		
		MOVLW	11111111B
		XORWF	R_LED_LIGHT,W
		BTFSC	STATUS,Z
		GOTO	INTERRUPT_LED_END
		
		BCF		R_LED_LIGHT,7		
		MOVFW	R_LED_LIGHT
		MOVWF	PT2CON
		MOVWF	LEDTEST2        ; IO - HZ		

		MOVLW	01111011B
		MOVWF	PT2

INTERRUPT_LED_END:
		BCF		STATUS,C
		RLF		R_LED_DUTY,F
		;根据点灯个数做电流调整	
		;111 110 :10MA 
		;101 	 :15MA 
		;100 	 :20MA
		;011	 :25MA
		;010	 :30MA
		;001	 :40MA
		;000	 :50MA	
		MOVFW	R_LED_DUTY
		ADDPCW	
		NOP
		NOP
		MOVLW	11111000B			 ; 		1, 10MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	10011000B			 ;		2, 20MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	01011000B			 ;		3, 30MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	00111000B			 ;      4, 40MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	00011000B			 ;		5, 50MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	00011000B			 ;	    6, 50MA
		GOTO	INTERRUPT_LED_END1
		MOVLW	00011000B			 ;	    7, 50MA
		GOTO	INTERRUPT_LED_END1
INTERRUPT_LED_END1:
		MOVWF	LEDCON1	
		;根据点灯个数做时间调整
		;1、不做电流调整时候的配置 80 100 120 160 200 240
		MOVFW	R_LED_DUTY
		ADDPCW
		NOP
		NOP
		MOVLW	110			         ;	    1
		GOTO	INTERRUPT_LED_END2
		MOVLW	110			         ;	    2
		GOTO	INTERRUPT_LED_END2
		MOVLW	110			         ;	    3
		GOTO	INTERRUPT_LED_END2
		MOVLW	110			         ;	    4
		GOTO	INTERRUPT_LED_END2
		MOVLW	110			         ;	    5
		GOTO	INTERRUPT_LED_END2
		MOVLW	180			         ;	    6
		GOTO	INTERRUPT_LED_END2
		MOVLW	250			         ;	    7
		GOTO	INTERRUPT_LED_END2
INTERRUPT_LED_END2:	
		MOVWF	TM1IN
		
		